apiVersion: v2
kubeVersion: '>=1.23.0-0'
name: seerr-chart
description: Sinerr helm chart for Kubernetes
type: application
version: 3.8.0
# renovate: image=ghcr.io/thelinyue/sinerr
appVersion: 'v3.4.0'
maintainers:
  - name: Sinerr Team
    url: https://github.com/orgs/thelinyue/people
sources:
  - https://github.com/thelinyue/sinerr/tree/main/charts/seerr-chart
home: https://github.com/thelinyue/sinerr
